### ISSUE TITLE
AttributeError: module 'corneto.methods.carnival' has no attribute 'select_mip_solver'

### ISSUE THREAD

**Issue by gianfilippo** [saezlab/corneto#12]
Hi,

I am implementing the Liana+ tutorial with my own data.

I am getting an error at the "Find Causal Network" step:
df_res, problem = li.mt.find_causalnet(prior_graph, input_scores, output_scores, node_weights, node_cutoff=0.1, max_penalty=1, min_penalty=0.01, edge_penalty=0.1,verbose=True, max_runs=50, stable_runs=10, solver='gurobi')

This results in the following output:
Total positive/negative scores of the inputs and outputs:
 - (-) input nodes: -7.810769193348582
 - (+) input nodes: 20.494407934579563
 - (-) output nodes: 0
 - (+) output nodes: 56.59489059448242
 - abs total (inputs + outputs): 84.90006772241057
Building CORNETO problem...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.conda/envs/Liana+/lib/python3.11/site-packages/liana/method/fun/_causalnet.py", line 193, in find_causalnet
    P, G = cn.methods.carnival._extended_carnival_problem(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'corneto.methods.carnival' has no attribute '_extended_carnival_problem'

Can you please help ?

Thanks

**Comment by pablormier** [comment]
LIANA+ depends on CORNETO 0.9.1-alpha.5. Please make sure that you have installed this version in your environment:

`pip install corneto==0.9.1-alpha.5 --force-reinstall`

@dbdimitrov we might need to indicate in LIANA the strict version of CORNETO 😃

**Comment by dbdimitrov** [comment]
@pablormier it is set to it but it's optional so I can't enforce unless installed with the extras param 😐
